import { DisplayedTexts } from "./DisplayedTexts";

/** Category + emoji + lowercase search tokens (English). */
export type EmojiPickerItem = {
	emoji: string;
	tags: string;
};

export type EmojiPickerCategory = {
	label: string;
	items: EmojiPickerItem[];
};

function I(emoji: string, tags: string): EmojiPickerItem {
	return { emoji, tags: tags.toLowerCase() };
}

export const EMOJI_PICKER_CATEGORIES: EmojiPickerCategory[] = [
	{
		label: DisplayedTexts.emojiCategories.smileys,
		items: [
			I("😀", "smile grin happy"),
			I("😃", "smile eyes mouth open happy"),
			I("😄", "smile eyes closed"),
			I("😁", "beaming grin"),
			I("😅", "sweat smile nervous"),
			I("😂", "joy tears laugh"),
			I("🤣", "rofl laugh floor"),
			I("😊", "blush smile"),
			I("😇", "halo angel innocent"),
			I("🙂", "slight smile"),
			I("😉", "wink"),
			I("😌", "relieved"),
			I("😍", "heart eyes love"),
			I("🥰", "hearts love smile"),
			I("😘", "kiss heart"),
			I("😗", "kiss"),
			I("😙", "kiss smile eyes"),
			I("😚", "kiss closed eyes"),
			I("😋", "yum tongue delicious"),
			I("😛", "tongue"),
			I("😜", "wink tongue"),
			I("🤪", "zany"),
			I("😝", "squint tongue"),
			I("🤑", "money mouth"),
			I("🤗", "hug hugging"),
			I("🤭", "hand mouth oops"),
			I("🤫", "shush quiet"),
			I("🤔", "thinking hmm"),
			I("🤐", "zipper mouth"),
			I("🤨", "raised eyebrow"),
			I("😐", "neutral"),
			I("😑", "expressionless"),
			I("😶", "no mouth"),
			I("😏", "smirk"),
			I("😒", "unamused"),
			I("🙄", "roll eyes"),
			I("😬", "grimace awkward"),
			I("😮‍💨", "exhale sigh relief"),
			I("🤥", "lying pinocchio"),
			I("😌", "relieved calm"),
			I("😔", "pensive sad"),
			I("😪", "sleepy"),
			I("🤤", "drool"),
			I("😴", "sleep zzz"),
			I("😷", "mask sick"),
			I("🤒", "thermometer sick"),
			I("🤕", "bandage hurt"),
			I("🤢", "nauseated"),
			I("🤮", "vomit"),
			I("🥵", "hot face"),
			I("🥶", "cold freeze"),
			I("😵", "dizzy"),
			I("🤯", "exploding head mind blown"),
		],
	},
	{
		label: DisplayedTexts.emojiCategories.gesturesPeople,
		items: [
			I("👋", "wave hand hello bye"),
			I("🤚", "raised hand"),
			I("✋", "stop hand"),
			I("🖐", "fingers splayed hand"),
			I("👌", "ok perfect"),
			I("🤌", "pinched fingers"),
			I("🤏", "pinching small"),
			I("✌️", "peace victory"),
			I("🤞", "fingers crossed luck"),
			I("🤟", "love you hand"),
			I("🤘", "rock horns"),
			I("👍", "thumbs up yes good"),
			I("👎", "thumbs down no"),
			I("👏", "clap applause"),
			I("🙌", "raised hands celebrate"),
			I("🫶", "heart hands"),
			I("🙏", "pray thanks please"),
			I("💪", "flex muscle strong"),
			I("🦾", "mechanical arm"),
			I("🧠", "brain think"),
			I("👀", "eyes look"),
			I("🫡", "salute"),
			I("🫂", "people hug"),
			I("👤", "silhouette person"),
			I("👥", "people busts group"),
			I("🧑", "person adult"),
			I("👨", "man"),
			I("👩", "woman"),
			I("🧒", "child"),
			I("👶", "baby"),
			I("🧓", "older adult"),
			I("🙋", "raising hand question"),
			I("🙇", "bow sorry thanks"),
			I("💁", "information desk tipping hand"),
			I("🙆", "ok gesture"),
			I("🙅", "no gesture"),
		],
	},
	{
		label: DisplayedTexts.emojiCategories.nature,
		items: [
			I("🐶", "dog puppy"),
			I("🐱", "cat kitten"),
			I("🐭", "mouse"),
			I("🐹", "hamster"),
			I("🐰", "rabbit bunny"),
			I("🦊", "fox"),
			I("🐻", "bear"),
			I("🐼", "panda"),
			I("🐨", "koala"),
			I("🐯", "tiger"),
			I("🦁", "lion"),
			I("🐮", "cow"),
			I("🐷", "pig"),
			I("🐸", "frog"),
			I("🐵", "monkey"),
			I("🐔", "chicken"),
			I("🐧", "penguin"),
			I("🐦", "bird"),
			I("🦆", "duck"),
			I("🦉", "owl"),
			I("🐝", "bee honey"),
			I("🦋", "butterfly"),
			I("🐢", "turtle"),
			I("🐍", "snake"),
			I("🐙", "octopus"),
			I("🦀", "crab"),
			I("🌵", "cactus"),
			I("🎄", "christmas tree"),
			I("🌲", "evergreen tree"),
			I("🌳", "tree"),
			I("🌴", "palm"),
			I("🌷", "tulip flower"),
			I("🌹", "rose"),
			I("🌻", "sunflower"),
			I("🌼", "blossom"),
			I("🌙", "moon crescent"),
			I("⭐", "star"),
			I("🌟", "glowing star"),
			I("✨", "sparkles"),
			I("🔥", "fire hot lit"),
			I("🌈", "rainbow"),
			I("☀️", "sun sunny"),
			I("⛅", "cloud sun"),
			I("🌧", "rain cloud"),
			I("❄️", "snowflake cold"),
		],
	},
	{
		label: DisplayedTexts.emojiCategories.foodDrink,
		items: [
			I("🍎", "apple fruit red"),
			I("🍊", "orange"),
			I("🍋", "lemon citrus"),
			I("🍌", "banana"),
			I("🍇", "grapes"),
			I("🍓", "strawberry berry"),
			I("🫐", "blueberries"),
			I("🍑", "peach"),
			I("🥝", "kiwi"),
			I("🍅", "tomato"),
			I("🥕", "carrot"),
			I("🌽", "corn"),
			I("🍞", "bread"),
			I("🥐", "croissant"),
			I("🧀", "cheese"),
			I("🍕", "pizza"),
			I("🍔", "burger hamburger"),
			I("🍟", "fries"),
			I("🌭", "hot dog"),
			I("🍿", "popcorn"),
			I("🧁", "cupcake"),
			I("🎂", "cake birthday"),
			I("🍪", "cookie"),
			I("☕", "coffee tea hot drink"),
			I("🍵", "tea cup"),
			I("🧃", "juice drink box"),
			I("🥤", "cup straw soda"),
			I("🍺", "beer"),
			I("🍷", "wine glass"),
			I("🥂", "champagne clink cheers"),
		],
	},
	{
		label: DisplayedTexts.emojiCategories.activity,
		items: [
			I("⚽", "soccer football ball"),
			I("🏀", "basketball"),
			I("🎾", "tennis"),
			I("🏈", "american football"),
			I("🎱", "8 ball pool"),
			I("🎮", "video game controller"),
			I("🎯", "dart target"),
			I("🎲", "dice game"),
			I("🎭", "theater drama masks"),
			I("🎨", "art palette paint"),
			I("🎬", "clapper movie film"),
			I("🎤", "mic microphone karaoke"),
			I("🎧", "headphones music"),
			I("🎵", "music note"),
			I("🎸", "guitar"),
			I("🎹", "piano keyboard"),
			I("🎪", "circus tent"),
			I("🎁", "gift present"),
			I("🎉", "party popper celebrate"),
			I("🎊", "confetti"),
			I("🏆", "trophy win"),
			I("🥇", "gold medal first"),
			I("🚴", "biking bicycle"),
			I("🏃", "running jog"),
			I("🧘", "yoga meditate"),
			I("⛷", "ski skiing"),
		],
	},
	{
		label: DisplayedTexts.emojiCategories.travelPlaces,
		items: [
			I("🚗", "car auto"),
			I("🚕", "taxi"),
			I("🚌", "bus"),
			I("🚎", "trolleybus"),
			I("🏎", "race car"),
			I("🚲", "bike bicycle"),
			I("✈️", "airplane plane fly"),
			I("🚀", "rocket ship launch"),
			I("🛸", "ufo flying saucer"),
			I("🚢", "ship boat"),
			I("⛵", "sailboat"),
			I("🗺", "map world"),
			I("🗽", "statue liberty new york"),
			I("🗼", "tower tokyo"),
			I("🏰", "castle"),
			I("🏠", "house home"),
			I("🏢", "office building"),
			I("🏥", "hospital"),
			I("🏫", "school"),
			I("🏬", "department store"),
			I("🌋", "volcano"),
			I("🏔", "snow mountain"),
			I("🏖", "beach umbrella"),
			I("🏝", "desert island"),
		],
	},
	{
		label: DisplayedTexts.emojiCategories.objects,
		items: [
			I("⌚", "watch time"),
			I("📱", "phone mobile iphone"),
			I("💻", "laptop computer"),
			I("⌨️", "keyboard"),
			I("🖥", "desktop monitor"),
			I("🖨", "printer"),
			I("🕯", "candle"),
			I("💡", "light bulb idea"),
			I("🔦", "flashlight torch"),
			I("📷", "camera photo"),
			I("🎥", "movie camera"),
			I("📞", "telephone"),
			I("📺", "tv television"),
			I("📻", "radio"),
			I("⏰", "alarm clock"),
			I("⌛", "hourglass time"),
			I("📅", "calendar date"),
			I("📌", "pin pushpin"),
			I("📎", "paperclip"),
			I("✏️", "pencil write"),
			I("🖊", "pen"),
			I("📁", "folder files"),
			I("📂", "folder open"),
			I("🗂", "card index dividers"),
			I("📋", "clipboard"),
			I("📖", "book open read"),
			I("📚", "books stack"),
			I("🔖", "bookmark"),
			I("💼", "briefcase work"),
			I("🛠", "hammer wrench tools"),
			I("🔧", "wrench"),
			I("🔨", "hammer"),
			I("⚙️", "gear settings"),
			I("💊", "pill medicine health"),
			I("🩹", "bandage"),
			I("🔗", "link chain"),
		],
	},
	{
		label: DisplayedTexts.emojiCategories.symbols,
		items: [
			I("❤️", "heart love red"),
			I("🧡", "orange heart"),
			I("💛", "yellow heart"),
			I("💚", "green heart"),
			I("💙", "blue heart"),
			I("💜", "purple heart"),
			I("🖤", "black heart"),
			I("💔", "broken heart"),
			I("❣️", "heart exclamation"),
			I("💯", "100 hundred perfect"),
			I("✨", "sparkles magic"),
			I("⭐", "star"),
			I("✅", "check mark done yes"),
			I("❌", "cross mark no"),
			I("⚠️", "warning caution"),
			I("⛔", "no entry stop"),
			I("🚫", "prohibited banned"),
			I("♻️", "recycle"),
			I("✳️", "asterisk"),
			I("❓", "question"),
			I("❗", "exclamation"),
			I("💤", "zzz sleep"),
			I("💭", "thought bubble"),
			I("💬", "speech balloon chat"),
			I("🏁", "checkered flag finish"),
			I("🚩", "flag triangular"),
		],
	},
];
