/**
 * All user-visible copy for the plugin (UI labels, notices, tooltips, empty states).
 * Edit strings here rather than hunting through components.
 */

export const DisplayedTexts = {
	main: {
		ribbonNewFile: (ext: string) => `New .${ext} file`,
		commandNewTimeline: (ext: string) => `New ${ext} timeline`,
		noticeSaveFailed: "Could not save timeline file. See console.",
		noticeCreateFailed: "Could not create timeline file. See console.",
		noticeFileNotCreated: "Timeline file was not created.",
		newFileBasename: "Timeline",
	},

	settings: {
		heading: "Timeline Planner",
		intro: (ext: string) => `Timelines live in dedicated \`.${ext}\` files (JSON).\nDouble-click one in the vault to open the planner,\nor use the ribbon / command to create a new file next to the active note (or in the vault root if nothing is open).`,
		defaultBarColorName: "Default task bar color",
		defaultBarColorDesc: "Pick a color for bars that have no per-task color.\nClear (×) to use the theme accent (gradient bar).\nWhen accent is active, the swatch is a neutral preview until you choose a color.",
		useThemeAccentTooltip: "Use theme accent",
		taskBarStackBreakpointName: "Compact task bar breakpoint",
		taskBarStackBreakpointDesc: "When a bar is narrower than this many pixels, the title stacks above the state control (zoom affects bar width in px).\nHigher = stay on one row longer while zoomed out; lower = stack sooner.\nRange: 120-600.",
		timelineZoomDayStepName: "Timeline zoom step (days)",
		timelineZoomDayStepDesc: "Total days added or removed per zoom (timeline +/- or Ctrl/⌘+scroll).\nThe change is split across both ends of the visible range (centered zoom); odd steps alternate which side gets the extra day.\nRange: 1-30.",
		taskStatesHeading: "Task states",
		taskStatesSummaryDesc: "Workflow states (name + color) for tasks on the bar and in the editor.\nOpens in a separate window.",
		openTaskStatesSettingsButton: "Configure task states...",
		taskStatesIntro: "Define states you can assign to tasks (shown on the bar and in the edit dialog).\nEach state has a name and color.",
		taskStateNameLabel: "Name",
		taskStateColorLabel: "Color",
		addTaskStateButton: "Add state",
		newTaskStateDefaultName: "New state",
		removeTaskStateTooltip: "Remove this state",

		emojiPickerHeading: "Emoji picker",
		emojiPickerSummaryDesc: "Categories and emojis for the task editor.\nOpens a separate window — useful for large custom sets.",
		openEmojiPickerSettingsButton: "Configure emoji picker...",
		emojiPickerIntro: "Categories and emojis shown when choosing a task emoji. Add work-specific sets or trim the defaults. Search in the picker matches category names and the tags you set per emoji.",
		emojiPickerRestoreDefaults: "Restore default emoji set",
		emojiPickerRestoreDefaultsTooltip: "Replace all categories with the plugin's built-in list (current customizations are lost).",
		emojiCategoryNameLabel: "Category name",
		emojiCategoryUnnamed: "Unnamed category",
		emojiCategorySummaryCount: (n: number) => n === 1 ? "1 emoji" : `${n} emojis`,
		emojiCategoryRemoveTooltip: "Remove this category",
		emojiItemEmojiLabel: "Emoji",
		emojiItemTagsDesc: "Space-separated words used when searching in the picker (stored lowercase).",
		emojiItemRemoveTooltip: "Remove this emoji",
		addEmojiCategoryButton: "Add category",
		addEmojiItemButton: "Add emoji to this category",
		newEmojiCategoryDefaultName: "New category",
	},

	taskModal: {
		title: "Edit task",
		fieldTitle: "Title",
		fieldEmoji: "Emoji",
		fieldEmojiDesc: "Optional icon before the task title on the timeline.",
		chooseEmoji: "Choose emoji",
		removeEmojiTooltip: "Remove emoji",
		fieldStartDate: "Start date",
		fieldEndDate: "End date",
		fieldBarColor: "Bar color",
		clearBarColorTooltip: "Clear — use plugin default",
		fieldNotes: "Notes",
		fieldTaskState: "State",
		taskStateNone: "None",
		save: "Save",
		barColorDescLead: "Obsidian color picker (#rrggbb).\nClear (×) to use the plugin default",
		barColorDescWithPluginDefault: (c: string) => ` (${c})`,
		barColorDescNoDefault: " (or theme accent if none)",
		barColorDescTail: ". Non-hex CSS colors are kept until you change the swatch.",
	},

	emojiModal: {
		title: "Choose emoji",
		searchPlaceholder: "Search by keyword or category...",
		noMatches: "No matches — try another word.",
	},

	/** Section titles for built-in emoji categories (`data/defaultEmojiPicker.json` uses these `nameKey`s). */
	emojiCategories: {
		smileys: "Smileys",
		gesturesPeople: "Gestures & people",
		nature: "Nature",
		foodDrink: "Food & drink",
		activity: "Activity",
		travelPlaces: "Travel & places",
		objects: "Objects",
		symbols: "Symbols",
	},

	timeline: {
		viewTitle: "Timeline",
		newTask: "New task",
		jumpToToday: "Jump to today",
		navEarlierAria: "Earlier",
		navLaterAria: "Later",

		zoomTitle: "Ctrl + Scroll on the timeline to change how many days fit the pane (columns fill the width). Zoom grows or shrinks the range from both ends (see plugin setting: zoom step).",
		zoomLabel: "Zoom",
		zoomOutAria: "Show more days (zoom out)",
		zoomInAria: "Show fewer days (zoom in)",
		
		shiftSelectionLabel: "Shift selection",
		nudgeEarlierTitle: "Move all selected tasks one day earlier (Ctrl+click bars to select)",
		nudgeLaterTitle: "Move all selected tasks one day later (Ctrl+click bars to select)",

		scrollRegionTitle: "Right Click-drag: move up/down through tasks,\nleft/right to change which days are visible.\nWheel: scroll. Ctrl + Scroll: show more or fewer days in the pane.",
		noticeParseError: (ext: string) => `Could not parse this .${ext} file (invalid JSON?).\nUsing empty planner.`,
		noticeNoFile: "No timeline file loaded.",
		noticeNoSelection: "No tasks selected. Ctrl+click bars to select.",
		emptyNoFileLoaded: "No .zly-timeline file loaded.",
		emptyNoTasks: 'No tasks yet. Click "New task" to add one.',
		reorderHandleGlyph: "⋮⋮",
		reorderTitle:
			"Drag to reorder. Hold Ctrl (⌘ on Mac) and drag the handle up or down to place a duplicate above or below.",
		deleteTaskSymbol: "x",
		deleteTask: "Delete this task.",
		outsideRangeArrowTitleLeft: (firstVisibleDay: string) => `Task is earlier — ends before ${firstVisibleDay} (left of the timeline).`,
		outsideRangeArrowTitleRight: (lastVisibleDay: string) => `Task is later — starts after ${lastVisibleDay} (right of the timeline).`,
		jumpToTaskButton: "Jump to task",
		jumpToTaskTitle: "Scroll the timeline so this task appears in the day grid",
		barTitle: "Double-click to edit.\nCtrl+click to multi-select, or drag on empty track to box-select.\nDrag horizontally to move in time; drag vertically to reorder.\nCan also use ⋮⋮ on the left side of the track to reorder vertically.",
		untitledTaskLabel: "[untitled]",
		
		newTaskDefaultTitle: "New task",
		noticeTaskAdded: "Task added.",
		noticeTaskRemoved: "Task removed.",
		taskStateSelectTitle: "Task state",
	},
} as const;
